# Generated by Django 4.2.13 on 2025-05-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallets", "0021_rename_ticker_new_transaction_ticker"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisnatBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_de_transaction", models.DateField(blank=True, null=True)),
                ("date_de_reglement", models.DateField()),
                (
                    "type_de_transaction",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "classe_d_actif",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("marche", models.CharField(blank=True, max_length=8, null=True)),
                ("quantite", models.IntegerField(blank=True, null=True)),
                (
                    "prix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "commission_payee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "devise_du_prix",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "montant_de_l_operation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "devise_du_compte",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("numero_id", models.IntegerField(blank=True, null=True)),
                (
                    "symbole",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallets.ticker",
                    ),
                ),
                (
                    "wallet",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="book_disnat",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_de_reglement"],
            },
        ),
        migrations.CreateModel(
            name="CryptoBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_id", models.IntegerField(blank=True, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("price_buy", models.DateField(blank=True, null=True)),
                ("price_sold", models.DateField(blank=True, null=True)),
                (
                    "profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("date_buy", models.DateField(blank=True, null=True)),
                ("date_sold", models.DateField(blank=True, null=True)),
                (
                    "ticker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallets.ticker",
                    ),
                ),
                (
                    "wallet",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="book_crypto",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_sold"],
            },
        ),
    ]
