# Generated by Django 4.2.13 on 2025-05-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptobook",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wallets.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="disnatbook",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wallets.wallet",
            ),
        ),
    ]
