# Generated by Django 4.2.13 on 2025-05-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0004_alter_cryptobook_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptobook",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cryptobook",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cryptobook",
            name="type",
            field=models.CharField(
                choices=[("purchase", "Purchase"), ("sell", "Sell")],
                default="purchase",
                max_length=20,
            ),
        ),
    ]
