# Generated by Django 4.2.13 on 2025-05-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounting",
            "0005_alter_cryptobook_price_alter_cryptobook_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptobook",
            name="ticker",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="disnatbook",
            name="symbole",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
