# Generated by Django 4.2.13 on 2025-05-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0007_rename_ticker_cryptobook_crypto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptobook",
            name="fees",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cryptobook",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
