# Generated by Django 4.2.13 on 2024-06-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0007_trader_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="type",
            field=models.CharField(
                choices=[("crypto", "Crypto"), ("equity", "Equity")],
                default="crypto",
                max_length=20,
            ),
        ),
    ]
