# Generated by Django 4.2.13 on 2024-06-30 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0009_alter_asset_ticker_alter_asset_trader"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="paid",
        ),
    ]
