# Generated by Django 4.2.13 on 2024-11-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0012_asset_staking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="staking",
            field=models.BooleanField(default=False),
        ),
    ]
