# Generated by Django 4.2.13 on 2025-05-23 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0027_alter_tradingplatform_logo"),
        ("accounts", "0003_alter_user_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraderCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unername", models.CharField(blank=True, max_length=128, null=True)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                ("twofa", models.CharField(blank=True, max_length=128, null=True)),
                ("api_key", models.CharField(blank=True, max_length=128, null=True)),
                ("secret", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "trader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="wallets.tradingplatform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
