# Generated by Django 4.2.13 on 2025-05-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_tradercredentials_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradercredentials",
            name="uid",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="tradercredentials",
            name="api_key",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
