# Generated by Django 4.2.13 on 2026-04-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_tradercredentials_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
