# Generated by Django 4.2.13 on 2025-05-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_tradercredentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradercredentials",
            name="api_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="tradercredentials",
            name="password",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="tradercredentials",
            name="secret",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="tradercredentials",
            name="twofa",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
