# Generated by Django 4.2.13 on 2024-06-25 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0009_alter_asset_ticker_alter_asset_trader"),
        ("wallets", "0004_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="ticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="assets.ticker",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="trader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="assets.trader",
            ),
        ),
    ]
