# Generated by Django 4.2.13 on 2024-06-25 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0005_alter_transaction_ticker_alter_transaction_trader"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="change",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[("cad", "CAD"), ("usd", "USD")], default="cad", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="fees",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
