# Generated by Django 4.2.13 on 2024-06-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0009_alter_asset_ticker_alter_asset_trader"),
        ("wallets", "0006_transaction_change_transaction_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="asset",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction",
                to="assets.asset",
            ),
        ),
    ]
