# Generated by Django 4.2.13 on 2024-06-30 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0010_alter_profit_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="change",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="fees",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
