# Generated by Django 4.2.13 on 2024-07-02 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0013_alter_transfer_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="transfer",
            options={"ordering": ["-date"]},
        ),
    ]
