# Generated by Django 4.2.13 on 2024-07-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0014_alter_transaction_options_alter_transfer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
