# Generated by Django 4.2.13 on 2025-04-30 18:33

from django.db import migrations, models
import django.db.models.deletion
import wallets.models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0016_alter_asset_options"),
        ("wallets", "0016_wallet_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to=wallets.models.upload_location
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "fees_buy",
                    models.CharField(
                        choices=[("money", "Money"), ("crypto", "Crypto")],
                        default="money",
                        max_length=20,
                    ),
                ),
                (
                    "fees_sell",
                    models.CharField(
                        choices=[("money", "Money"), ("crypto", "Crypto")],
                        default="money",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="wallet",
            name="asset",
            field=models.ManyToManyField(
                blank=True, related_name="wallet", to="assets.asset"
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="trader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to="wallets.tradingplatform",
            ),
        ),
    ]
