# Generated by Django 4.2.13 on 2025-05-01 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0017_tradingplatform_alter_wallet_asset_wallet_trader"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticker_new",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=16)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("crypto", "Crypto"), ("equity", "Equity")],
                        default="crypto",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tradingplatform",
            name="type",
            field=models.CharField(
                choices=[("crypto", "Crypto"), ("equity", "Equity")],
                default="crypto",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="trading_platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="wallets.tradingplatform",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[("cad", "CAD"), ("usd", "USD")], default="cad", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ticker_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="wallets.ticker_new",
            ),
        ),
    ]
