# Generated by Django 4.2.13 on 2025-05-01 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0020_rename_ticker_new_ticker"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="ticker_new",
            new_name="ticker",
        ),
    ]
