# Generated by Django 4.2.13 on 2025-05-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0021_rename_ticker_new_transaction_ticker"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="lastviewed",
            new_name="last_viewed",
        ),
        migrations.AddField(
            model_name="wallet",
            name="last_view",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
