# Generated by Django 4.2.13 on 2025-05-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0025_tradingplatform_logo_tradingplatform_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingplatform",
            name="logo",
            field=models.FileField(
                blank=True,
                choices=[
                    (
                        "images/logos/logo-courtage-ligne-fr.png",
                        "images/logos/logo-courtage-ligne-fr.png",
                    ),
                    ("images/logos/ndax.png", "images/logos/ndax.png"),
                    ("images/logos/coinbase.png", "Coinbase"),
                ],
                default="images/logos/logo-courtage-ligne-fr.png",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="tradingplatform",
            name="url",
            field=models.URLField(
                blank=True,
                choices=[
                    ("https://www.disnat.com/", "https://www.disnat.com/"),
                    ("https://portal.ndax.io/", "https://portal.ndax.io/"),
                    ("https://www.coinbase.com/", "https://www.coinbase.com/"),
                ],
                default="https://www.disnat.com/",
                null=True,
            ),
        ),
    ]
