# Generated by Django 4.2.13 on 2025-07-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0028_alter_ticker_options_alter_wallet_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profit",
            name="profit",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
