# Generated by Django 4.2.13 on 2025-08-06 18:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0029_alter_profit_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="balance_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
