# Generated by Django 4.2.13 on 2024-06-25 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0002_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="lastviewed",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="type",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                default="deposit",
                max_length=20,
            ),
        ),
    ]
