# Generated by Django 4.2.13 on 2024-06-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0007_transaction_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("purchase", "Purchase"), ("sell", "Sell")],
                default="purchase",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[("cad", "CAD"), ("usd", "USD")],
                default="purchase",
                max_length=4,
            ),
        ),
    ]
