# Generated by Django 4.2.13 on 2024-06-28 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0009_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profit",
            name="profit",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
