# Generated by Django 4.2.13 on 2024-07-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0011_alter_transaction_change_alter_transaction_fees_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["date"]},
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[("cad", "CAD"), ("usd", "USD")], default="buy", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")], default="buy", max_length=10
            ),
        ),
    ]
