# Generated by Django 4.2.13 on 2024-07-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wallets",
            "0012_alter_transaction_options_alter_transaction_currency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("interest", "Interest"),
                    ("dividends", "Dividends"),
                    ("withdrawal", "Withdrawal"),
                ],
                default="deposit",
                max_length=20,
            ),
        ),
    ]
