# Generated by Django 4.2.13 on 2025-04-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0016_alter_asset_options"),
        ("wallets", "0015_transfer_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="asset",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="wallet", to="assets.asset"
            ),
        ),
    ]
