# Generated by Django 4.2.13 on 2025-05-01 03:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0018_ticker_new_tradingplatform_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="ticker",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="trader",
        ),
    ]
