# Generated by Django 4.2.13 on 2025-05-01 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0019_remove_transaction_ticker_remove_transaction_trader"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ticker_new",
            new_name="Ticker",
        ),
    ]
