# Generated by Django 4.2.13 on 2025-05-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0022_rename_lastviewed_wallet_last_viewed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="type",
            field=models.CharField(
                choices=[("crypto", "Crypto"), ("equity", "Action")],
                default="crypto",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tradingplatform",
            name="fees_buy",
            field=models.CharField(
                choices=[("money", "Monnaie"), ("crypto", "Crypto")],
                default="money",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tradingplatform",
            name="fees_sell",
            field=models.CharField(
                choices=[("money", "Monnaie"), ("crypto", "Crypto")],
                default="money",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tradingplatform",
            name="type",
            field=models.CharField(
                choices=[("crypto", "Crypto"), ("equity", "Action")],
                default="crypto",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("buy", "Achat"), ("sell", "Vente")],
                default="buy",
                max_length=10,
            ),
        ),
    ]
