# Generated by Django 4.2.13 on 2025-05-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0023_alter_ticker_type_alter_tradingplatform_fees_buy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradingplatform",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="tradingplatform",
            name="url",
        ),
        migrations.AlterField(
            model_name="tradingplatform",
            name="name",
            field=models.CharField(
                choices=[
                    ("Disnat", "Disnat"),
                    ("NDAX", "NDAX"),
                    ("Coinbase", "Coinbase"),
                ],
                default="Disnat",
                max_length=32,
            ),
        ),
    ]
