# Generated by Django 4.2.13 on 2025-05-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0024_remove_tradingplatform_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingplatform",
            name="logo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Disnat", "images/logos/logo-courtage-ligne-fr.png"),
                    ("NDAX", "images/logos/ndax.png"),
                    ("Coinbase", "images/logos/coinbase.png"),
                ],
                default="Disnat",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradingplatform",
            name="url",
            field=models.URLField(
                blank=True,
                choices=[
                    ("Disnat", "https://www.disnat.com/"),
                    ("NDAX", "https://portal.ndax.io/"),
                    ("Coinbase", "https://www.coinbase.com/"),
                ],
                default="Disnat",
                null=True,
            ),
        ),
    ]
