# Generated by Django 4.2.13 on 2025-05-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0026_alter_tradingplatform_logo_alter_tradingplatform_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingplatform",
            name="logo",
            field=models.FileField(
                blank=True,
                choices=[
                    (
                        "images/logos/logo-courtage-ligne-fr.png",
                        "images/logos/logo-courtage-ligne-fr.png",
                    ),
                    ("images/logos/ndax.png", "images/logos/ndax.png"),
                    ("images/logos/coinbase.png", "images/logos/coinbase.png"),
                ],
                default="images/logos/logo-courtage-ligne-fr.png",
                null=True,
                upload_to="",
            ),
        ),
    ]
