# Generated by Django 4.2.13 on 2025-07-11 04:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0027_alter_tradingplatform_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticker",
            options={"ordering": ["symbol"]},
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={"ordering": ["name"]},
        ),
    ]
