# Generated by Django 5.0.6 on 2024-05-09 19:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=16)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "current",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticker",
                        to="assets.ticker",
                    ),
                ),
            ],
        ),
    ]
