# Generated by Django 5.0.6 on 2024-05-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="monitor",
            field=models.BooleanField(default=False),
        ),
    ]
