# Generated by Django 4.2.13 on 2024-05-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_trader_asset_trader"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
