# Generated by Django 4.2.13 on 2024-05-21 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0005_asset_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["trader"]},
        ),
    ]
