# Generated by Django 4.2.13 on 2024-05-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0006_alter_asset_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="trader",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
