# Generated by Django 4.2.13 on 2024-07-02 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0010_remove_asset_paid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["trader", "-date"]},
        ),
    ]
