# Generated by Django 4.2.13 on 2024-11-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0011_alter_asset_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="staking",
            field=models.BooleanField(default=True),
        ),
    ]
