# Generated by Django 4.2.13 on 2025-01-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0013_alter_asset_staking"),
    ]

    operations = [
        migrations.AddField(
            model_name="trader",
            name="fees_buy",
            field=models.CharField(
                choices=[("money", "Money"), ("crypto", "Crypto")],
                default="money",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trader",
            name="fees_sell",
            field=models.CharField(
                choices=[("money", "Money"), ("crypto", "Crypto")],
                default="money",
                max_length=20,
            ),
        ),
    ]
