# Generated by Django 4.2.13 on 2025-01-16 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0014_trader_fees_buy_trader_fees_sell"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="fees_per_unit",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
