# Generated by Django 4.2.13 on 2025-04-24 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0015_asset_fees_per_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["trader", "-monitor", "staking", "-date"]},
        ),
    ]
