# Generated by Django 4.2.13 on 2025-05-01 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0016_alter_asset_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["-monitor", "staking", "-date"]},
        ),
        migrations.RemoveField(
            model_name="asset",
            name="ticker",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="trader",
        ),
        migrations.DeleteModel(
            name="Ticker",
        ),
        migrations.DeleteModel(
            name="Trader",
        ),
    ]
