# Generated by Django 4.2.13 on 2025-05-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_alter_cryptobook_wallet_alter_disnatbook_wallet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disnatbook",
            options={"ordering": ["date_de_reglement"]},
        ),
        migrations.AlterField(
            model_name="disnatbook",
            name="prix",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
    ]
