# Generated by Django 4.2.13 on 2025-05-06 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0003_alter_disnatbook_options_alter_disnatbook_prix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cryptobook",
            options={"ordering": ["date"]},
        ),
        migrations.RenameField(
            model_name="cryptobook",
            old_name="profit",
            new_name="fees",
        ),
        migrations.RenameField(
            model_name="cryptobook",
            old_name="date_buy",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="cryptobook",
            name="date_sold",
        ),
        migrations.RemoveField(
            model_name="cryptobook",
            name="price_buy",
        ),
        migrations.RemoveField(
            model_name="cryptobook",
            name="price_sold",
        ),
        migrations.AddField(
            model_name="cryptobook",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cryptobook",
            name="type",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
