# Generated by Django 4.2.13 on 2025-05-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0006_alter_cryptobook_ticker_alter_disnatbook_symbole"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cryptobook",
            old_name="ticker",
            new_name="crypto",
        ),
        migrations.AlterField(
            model_name="cryptobook",
            name="type",
            field=models.CharField(
                choices=[("ACHAT", "Achat"), ("VENTE", "Vente")],
                default="ACHAT",
                max_length=20,
            ),
        ),
    ]
